package com.ohmyguide.app.ui.theme.strings

import com.ohmyguide.app.ui.theme.AppStrings

object EnStrings : AppStrings {
    override val appName = "Oh My Guide"
    override val back = "Back"
    override val send = "Send"
    override val remove = "Remove"
    override val stop = "Stop"
    override val skip = "Skip"
    override val restore = "Restore"
    override val map = "Map"
    override val next = "Next"

    override val navHome = "Home"
    override val navExplore = "Explore"
    override val navPhrases = "Phrases"

    override val splashSubtitle = "Your Special Korea Tour Guide Service"

    override val welcomeGreeting = "Annyeong!"
    override val welcomeIntro = "I'm your Korea guide"
    override val welcomeDesc = "Find amazing places,\nnavigate like a local,\nand get personalized guides."
    override val signInGoogle = "Sign in with Google"
    override val signInHint = "One-tap sign in to get your personalized guide"
    override val loginSuccess = "You have successfully logged in."

    override val onboardLangPrompt = "Find the Best Spots Near You!\nTo give you the best experience,\nwhat language do you prefer?"
    override val onboardGenderPrompt = "Great! And what is your gender?"
    override val onboardAgePrompt = "Nice! How old are you?"
    override val onboardCountryPrompt = "Where are you from?"
    override val onboardCompanionPrompt = "Awesome! Who are you traveling with?"
    override val onboardGpsPrompt = "Perfect! Lastly, please allow location access so we can explore together."
    override val allowLocation = "Allow Location Access"
    override val enterAge = "Enter your age"
    override val yearsOld = " years old"
    override val ageConfirm = "I'm %d years old"
    override val selectCountry = "Select your country"
    override val female = "Female"
    override val male = "Male"
    override val friends = "Friends"
    override val family = "Family"
    override val solo = "Solo"
    override val partner = "Partner"

    override val detectingLocation = "Detecting your location..."
    override val yourLocation = "Your Location"
    override val categoryGreeting = "Hello! I'm Kkaebi.\nLet me find the perfect spots near you!"
    override val categoryPrompt = "Just tell me what you're into"
    override val categoryDone = "Great choices! Let me find the best spots for you."
    override val chooseInterests = "Choose what interests you!"
    override val addMoreOrSend = "Great pick! Add more or send"
    override val categoriesSelected = "categories selected"

    override val categoryNames = mapOf(
        "attraction" to "Attraction", "culture" to "Culture", "festival" to "Festival",
        "course" to "Course", "leports" to "Leports", "cafe" to "Cafes",
        "shopping" to "Shopping", "food" to "Food",
    )
    override val categorySubs = mapOf(
        "attraction" to "Landmarks & nature", "culture" to "Museums & history",
        "festival" to "Events & performances", "course" to "Travel routes",
        "leports" to "Leisure & sports", "cafe" to "Coffee & bakeries",
        "shopping" to "Markets & malls", "food" to "Dining & street eats",
    )

    override val findingSpots = "Finding amazing spots..."
    override val scanningNearby = "Scanning nearby places\nbased on your interests"

    override val curatingSpots = "Curating spots..."
    override val reset = "Reset"
    override val near = "Near"
    override val spots = "spots"
    override val yourArea = "your area"
    override val backToList = "Back to list"
    override val findOtherPlaces = "Find other places"
    override val goHere = "Go here"

    override val hotThisWeek = "Hot This Week"
    override val courses = "Courses"
    override val allCourses = "All Courses"
    override val kCulture = "K-Culture"
    override val explore = "Explore"
    override val trending = "TRENDING"
    override val diveIntoKCulture = "Dive into\nK-Culture"
    override val curatedCourses = "Curated courses by locals & K-fans"
    override val noCoursesFound = "No courses found"
    override val tryDifferentRegion = "Try a different region or category"
    override val exploreThisCourse = "Explore This Course"
    override val seeAllCourses = "See All Courses"
    override val swipeToDiscover = "Swipe to discover more"
    override val courseRoute = "COURSE ROUTE"
    override val startCourseNavi = "Start Course Navigation"
    override val courseProgress = "COURSE PROGRESS"
    override val rightHere = "Right here"

    override val destination = "Destination"
    override val tapToSeeRoutes = "Tap below to see available routes"
    override val viewTransitRoutes = "View Transit Routes"
    override val startNavigation = "Start Navigation"
    override val walk = "Walk"
    override val enjoyScenery = "Enjoy the scenery"
    override val transit = "Transit"
    override val busAndSubway = "Bus & Subway"
    override val taxi = "Taxi"
    override val taxiCar = "Taxi / Car"
    override val transfer = "Transfer"
    override val subway = "Subway"
    override val direct = "Direct"
    override val stopsUnit = "stops"

    override val walkingTo = "Walking to"
    override val transitTo = "Transit to"
    override val drivingTo = "Driving to"
    override val yesShowMe = "Yes, show me!"
    override val iveArrived = "I've Arrived!"
    override val listen = "Listen"
    override val photo = "Photo"
    override val prices = "Prices"

    override val loading = "Loading\u2026"
    override val nowPlaying = "Now playing\u2026"
    override val paused = "Paused"
    override val backToGuide = "Back to Guide"
    override val listenToGuide = "Listen to Guide"

    override val koreanPhrasesTitle = "\uD55C\uAD6D\uC5B4 \uAD6C\uBB38"
    override val koreanPhrasesSubtitle = "Korean Phrases for Travelers"
    override val saved = "saved"
    override val bookmarkHint = "Tap the bookmark to save phrases for quick access offline!"
    override val phrasesUnit = "phrases"

    override val myPage = "My Page"
    override val visitHistory = "Visit History"
    override val placesVisitedDesc = "Places you've been"
    override val bookmarks = "Bookmarks"
    override val savedPlacesDesc = "Saved places & phrases"
    override val storyArchive = "Story Archive"
    override val storiesListenedDesc = "Stories you've listened"
    override val language = "Language"
    override val notifications = "Notifications"
    override val on = "On"
    override val theme = "Theme"
    override val light = "Light"
    override val traveler = "Traveler"
    override val food = "Food"
    override val culture = "Culture"
    override val signOut = "Sign Out"
    override val ageUnit = " yrs"
    override val pickRecommendTitle = "Popular with Travelers Like You"
    override val pickRecommendDesc = "Based on big data from similar travelers"
    override val pickRecommendEmpty = "No recommendations available yet"
    override val editProfile = "Edit Profile"
    override val nationality = "Nationality"
    override val age = "Age"
    override val gender = "Gender"
    override val save = "Save"
    override val bookmarkEmpty = "No saved phrases yet. Tap to browse!"
    override val viewAllPhrases = "View All Phrases"
    override val picksForYou = "Picks for You"
    override val newPicksForYou = "New Picks for You"
    override val noPlacesFound = "No places found nearby. Try a different category!"
    override val sorryNoPlaces = "Sorry, I couldn't find places right now. Please try again!"
    override val freshPicks = "Here are fresh picks based on your taste!"
    override val mainFocusQuestion = "First, what's your main focus today?"
    override val vibeQuestion = "And what kind of vibe?"
    override val optionFood = "Local Food & Cafe"
    override val optionPhoto = "Photo Spots"
    override val optionShopping = "Shopping & Trends"
    override val optionActive = "Active & Bustling"
    override val optionCalm = "Calm & Healing"
    override val optionNightlife = "Nightlife"
    override val showMore = "Show more"
    override val moreSpots = "Here are more spots!"
    override val guideToPlace = "I'll guide you to %s! Keep going straight ahead."
    override val storyAboutPlace = "By the way, I know some interesting stories about %s!"
    override val usefulPhrases = "Here are some useful Korean phrases:"
    override val arrivedAt = "You've arrived at %s! Enjoy your visit!"
    override val nearbyPlacesAlong = "Here are some interesting places along your route:"
    override val nearbyPlacesLove = "Great! Here are some spots nearby you might love:"

    override val locating = "Locating..."
    override val mapView = "Map View"
    override val explorePlaces = "Explore places around you"

    override val hours = "Hours"
    override val fee = "Fee"
    override val distance = "Distance"
    override val preview = "Preview"
    override val placeNo = "NO"
    override val placeGo = "GO"

    override val transitRoutes = "Transit Routes"
    override val searchingRoutes = "Searching routes..."
    override val noTransitRoutes = "No transit routes found"
    override val tryWalkOrCar = "Try walking or car instead"
    override val filterAll = "All"
    override val busLabel = "Bus"
    override val busSubwayLabel = "Bus+Subway"
    override val minSuffix = "min"
    override val hourSuffix = "h"
    override val minWalkSuffix = "min walk"
    override val etaPrefix = "ETA"
    override val notAvailable = "N/A"
    override val stopsAway = "stops away"
    override val listenToStory = "Listen to Story"
    override val getOffAt = "Get off at"
    override val currentLocation = "Current Location"

    override val endNaviTitle = "End Navigation?"
    override val endNaviMessage = "Are you sure you want to stop navigating?"
    override val confirm = "End"
    override val cancel = "Cancel"
    override val movingToNextCourse = "Moving to the next spot!"

    override val noRecommendations = "No recommendations yet"
    override val noRecommendationsDesc = "Tell us your interests to get personalized spots"
    override val noSavedPhrases = "No saved phrases"
    override val noSavedPhrasesDesc = "Bookmark phrases to access them offline"
}