package com.ohmyguide.app.ui.theme.strings

import com.ohmyguide.app.ui.theme.AppStrings

object JaStrings : AppStrings {
    override val appName = "Oh My Guide"
    override val back = "戻る"
    override val send = "送信"
    override val remove = "削除"
    override val stop = "停止"
    override val skip = "スキップ"
    override val restore = "復元"
    override val map = "地図"
    override val next = "次へ"

    override val navHome = "ホーム"
    override val navExplore = "探索"
    override val navPhrases = "フレーズ"

    override val splashSubtitle = "あなただけの特別な韓国旅行ガイド"

    override val welcomeGreeting = "アンニョン! \uD83D\uDC4B"
    override val welcomeIntro = "韓国ガイドです"
    override val welcomeDesc = "素敵な場所を見つけ、\n地元の人のように移動し、\nパーソナルガイドを手に入れよう。"
    override val signInGoogle = "Googleでサインイン"
    override val signInHint = "ワンタップでログインしてガイドを手に入れよう"

    override val onboardLangPrompt = "近くのベストスポットを見つけよう！\n最高の体験のために、\nお好みの言語を選んでください。"
    override val onboardGenderPrompt = "いいですね！性別を教えてください。"
    override val onboardAgePrompt = "いいですね！おいくつですか？"
    override val onboardCountryPrompt = "どこの国から来ましたか？"
    override val onboardCompanionPrompt = "素晴らしい！誰と旅行していますか？"
    override val onboardGpsPrompt = "完璧！最後に、一緒に探検するために\n位置情報のアクセスを許可してください。"
    override val allowLocation = "位置情報のアクセスを許可"
    override val enterAge = "年齢を入力"
    override val yearsOld = "歳"
    override val female = "女性"
    override val male = "男性"
    override val friends = "友達"
    override val family = "家族"
    override val solo = "一人"

    override val detectingLocation = "位置を検出中..."
    override val yourLocation = "現在地"
    override val categoryGreeting = "やあ！Oh My Guideです\n今すぐ近くの最高のスポットを見つけます！"
    override val categoryPrompt = "興味のあることを教えてください"
    override val categoryDone = "素晴らしい選択！最高のスポットを探します... \uD83C\uDFAF"
    override val chooseInterests = "興味のあるものを選んでください！"
    override val addMoreOrSend = "いい選択！追加するか送信してください"
    override val categoriesSelected = "カテゴリー選択中"

    override val findingSpots = "素敵なスポットを探しています..."
    override val scanningNearby = "あなたの興味に基づいて\n近くの場所をスキャン中"

    override val curatingSpots = "スポットをキュレーション中..."
    override val reset = "リセット"
    override val near = "付近"
    override val spots = "スポット"
    override val yourArea = "このエリア"
    override val backToList = "リストに戻る"
    override val findOtherPlaces = "他の場所を探す"
    override val goHere = "ここへ行く"

    override val hotThisWeek = "今週の注目"
    override val courses = "コース"
    override val allCourses = "すべてのコース"
    override val kCulture = "K-Culture"
    override val explore = "探索"
    override val trending = "トレンド"
    override val diveIntoKCulture = "K-Cultureに\n飛び込もう"
    override val curatedCourses = "地元の人とK-ファンが厳選したコース"
    override val noCoursesFound = "コースが見つかりません"
    override val tryDifferentRegion = "別の地域やカテゴリーを試してみてください"
    override val courseRoute = "コースルート"
    override val startCourseNavi = "コースナビを開始"
    override val courseProgress = "コース進捗"
    override val rightHere = "すぐここ"

    override val destination = "目的地"
    override val tapToSeeRoutes = "下をタップして利用可能なルートを表示"
    override val viewTransitRoutes = "交通ルートを表示"
    override val startNavigation = "ナビを開始"
    override val walk = "徒歩"
    override val enjoyScenery = "景色を楽しむ"
    override val transit = "公共交通"
    override val busAndSubway = "バス＆地下鉄"
    override val taxi = "タクシー"
    override val taxiCar = "タクシー / 車"
    override val transfer = "乗り換え"
    override val subway = "地下鉄"
    override val direct = "直行"
    override val stopsUnit = "駅"

    override val walkingTo = "徒歩で移動中"
    override val transitTo = "交通機関で移動中"
    override val drivingTo = "車で移動中"
    override val yesShowMe = "はい、見せて！"
    override val iveArrived = "到着しました！"
    override val listen = "聴く"
    override val photo = "写真"
    override val prices = "料金"

    override val nowPlaying = "再生中\u2026"
    override val paused = "一時停止"
    override val backToGuide = "ガイドに戻る"

    override val koreanPhrasesTitle = "韓国語フレーズ"
    override val koreanPhrasesSubtitle = "旅行者のための韓国語フレーズ"
    override val saved = "保存済み"
    override val bookmarkHint = "ブックマークをタップしてオフラインで素早くアクセス！"
    override val phrasesUnit = "フレーズ"

    override val myPage = "マイページ"
    override val visitHistory = "訪問履歴"
    override val placesVisitedDesc = "訪れた場所"
    override val bookmarks = "ブックマーク"
    override val savedPlacesDesc = "保存した場所とフレーズ"
    override val storyArchive = "ストーリーアーカイブ"
    override val storiesListenedDesc = "聞いたストーリー"
    override val language = "言語"
    override val notifications = "通知"
    override val on = "オン"
    override val theme = "テーマ"
    override val light = "ライト"
    override val traveler = "旅行者"
    override val food = "食べ物"
    override val culture = "文化"
    override val signOut = "ログアウト"

    override val locating = "位置を確認中..."
    override val mapView = "地図ビュー"
    override val explorePlaces = "周辺のスポットを探索"

    override val hours = "営業時間"
    override val fee = "料金"
    override val distance = "距離"
    override val preview = "プレビュー"
    override val placeNo = "いいえ"
    override val placeGo = "行く"

    override val transitRoutes = "乗り換え案内"
    override val searchingRoutes = "ルート検索中..."
    override val noTransitRoutes = "交通ルートが見つかりません"
    override val tryWalkOrCar = "徒歩や車を試してみてください"
    override val filterAll = "すべて"
    override val busLabel = "バス"
    override val busSubwayLabel = "バス+地下鉄"
    override val minSuffix = "分"
    override val hourSuffix = "時間"
    override val minWalkSuffix = "分徒歩"
    override val etaPrefix = "到着予定"
    override val notAvailable = "利用不可"
    override val stopsAway = "駅前"
    override val listenToStory = "ストーリーを聴く"
    override val getOffAt = "下車駅:"
    override val currentLocation = "現在地"

    override val endNaviTitle = "ナビを終了しますか？"
    override val endNaviMessage = "案内を中断して前の画面に戻ります。"
    override val confirm = "終了"
    override val cancel = "キャンセル"

    override val noRecommendations = "おすすめスポットがまだありません"
    override val noRecommendationsDesc = "興味を教えてくれたらぴったりの場所を探します"
    override val noSavedPhrases = "保存したフレーズがありません"
    override val noSavedPhrasesDesc = "ブックマークしてオフラインでも確認しましょう"
}