package com.ohmyguide.app.ui.theme.strings

import com.ohmyguide.app.ui.theme.AppStrings

object KoStrings : AppStrings {
    override val appName = "Oh My Guide"
    override val back = "뒤로"
    override val send = "전송"
    override val remove = "삭제"
    override val stop = "중지"
    override val skip = "건너뛰기"
    override val restore = "복원"
    override val map = "지도"
    override val next = "다음"

    override val navHome = "홈"
    override val navExplore = "탐색"
    override val navPhrases = "회화"

    override val splashSubtitle = "당신만의 특별한 한국 여행 가이드"

    override val welcomeGreeting = "안녕! \uD83D\uDC4B"
    override val welcomeIntro = "당신의 한국 가이드예요"
    override val welcomeDesc = "멋진 장소를 발견하고,\n현지인처럼 이동하고,\n맞춤 가이드를 받아보세요."
    override val signInGoogle = "Google로 로그인"
    override val signInHint = "원터치 로그인으로 맞춤 가이드를 받아보세요"

    override val onboardLangPrompt = "주변 최고의 장소를 찾아보세요!\n최고의 경험을 위해,\n선호하는 언어를 선택해주세요."
    override val onboardGenderPrompt = "좋아요! 성별이 어떻게 되시나요?"
    override val onboardAgePrompt = "좋아요! 나이가 어떻게 되시나요?"
    override val onboardCountryPrompt = "어느 나라에서 오셨나요?"
    override val onboardCompanionPrompt = "멋져요! 누구와 여행하시나요?"
    override val onboardGpsPrompt = "완벽해요! 마지막으로, 함께 탐험할 수 있도록\n위치 접근을 허용해주세요."
    override val allowLocation = "위치 접근 허용"
    override val enterAge = "나이를 입력하세요"
    override val yearsOld = "세"
    override val female = "여성"
    override val male = "남성"
    override val friends = "친구"
    override val family = "가족"
    override val solo = "혼자"

    override val detectingLocation = "위치를 감지하는 중..."
    override val yourLocation = "현재 위치"
    override val categoryGreeting = "안녕! 나는 Oh My Guide야\n지금 바로 주변의 완벽한 장소를 찾아줄게!"
    override val categoryPrompt = "관심 있는 것을 알려주세요"
    override val categoryDone = "멋진 선택! 최고의 장소를 찾아볼게요... \uD83C\uDFAF"
    override val chooseInterests = "관심 있는 것을 선택하세요!"
    override val addMoreOrSend = "좋은 선택! 더 추가하거나 보내세요"
    override val categoriesSelected = "개 카테고리 선택됨"

    override val findingSpots = "멋진 장소를 찾는 중..."
    override val scanningNearby = "관심사를 기반으로\n주변 장소를 검색 중"

    override val curatingSpots = "장소 큐레이팅 중..."
    override val reset = "초기화"
    override val near = "주변"
    override val spots = "곳"
    override val yourArea = "내 주변"
    override val backToList = "목록으로"
    override val findOtherPlaces = "다른 장소 찾기"
    override val goHere = "여기로 가기"

    override val hotThisWeek = "이번 주 인기"
    override val courses = "코스"
    override val allCourses = "전체 코스"
    override val kCulture = "K-Culture"
    override val explore = "탐색"
    override val trending = "인기"
    override val diveIntoKCulture = "K-Culture에\n빠져보세요"
    override val curatedCourses = "현지인과 K-팬이 추천하는 코스"
    override val noCoursesFound = "코스를 찾을 수 없습니다"
    override val tryDifferentRegion = "다른 지역이나 카테고리를 시도해보세요"
    override val courseRoute = "코스 경로"
    override val startCourseNavi = "코스 내비게이션 시작"
    override val courseProgress = "코스 진행"
    override val rightHere = "바로 여기"

    override val destination = "목적지"
    override val tapToSeeRoutes = "아래를 터치하여 이용 가능한 경로 보기"
    override val viewTransitRoutes = "대중교통 경로 보기"
    override val startNavigation = "내비게이션 시작"
    override val walk = "도보"
    override val enjoyScenery = "경치를 즐기세요"
    override val transit = "대중교통"
    override val busAndSubway = "버스 & 지하철"
    override val taxi = "택시"
    override val taxiCar = "택시 / 차량"
    override val transfer = "환승"
    override val subway = "지하철"
    override val direct = "직행"
    override val stopsUnit = "정거장"

    override val walkingTo = "도보 이동 중"
    override val transitTo = "대중교통 이동 중"
    override val drivingTo = "차량 이동 중"
    override val yesShowMe = "네, 보여주세요!"
    override val iveArrived = "도착했어요!"
    override val listen = "듣기"
    override val photo = "사진"
    override val prices = "가격"

    override val nowPlaying = "재생 중\u2026"
    override val paused = "일시정지"
    override val backToGuide = "가이드로 돌아가기"

    override val koreanPhrasesTitle = "한국어 구문"
    override val koreanPhrasesSubtitle = "여행자를 위한 한국어 표현"
    override val saved = "저장됨"
    override val bookmarkHint = "북마크를 눌러 오프라인에서 빠르게 확인하세요!"
    override val phrasesUnit = "개 구문"

    override val myPage = "마이페이지"
    override val visitHistory = "방문 기록"
    override val placesVisitedDesc = "방문한 장소"
    override val bookmarks = "북마크"
    override val savedPlacesDesc = "저장된 장소 및 구문"
    override val storyArchive = "스토리 보관함"
    override val storiesListenedDesc = "들었던 스토리"
    override val language = "언어"
    override val notifications = "알림"
    override val on = "켜짐"
    override val theme = "테마"
    override val light = "라이트"
    override val traveler = "여행자"
    override val food = "음식"
    override val culture = "문화"
    override val signOut = "로그아웃"

    override val locating = "위치 확인 중..."
    override val mapView = "지도 보기"
    override val explorePlaces = "주변 장소를 탐색하세요"

    override val hours = "운영시간"
    override val fee = "요금"
    override val distance = "거리"
    override val preview = "미리보기"
    override val placeNo = "아니요"
    override val placeGo = "가기"

    override val transitRoutes = "대중교통 경로"
    override val searchingRoutes = "경로 검색 중..."
    override val noTransitRoutes = "대중교통 경로를 찾을 수 없어요"
    override val tryWalkOrCar = "도보나 차량을 이용해보세요"
    override val filterAll = "전체"
    override val busLabel = "버스"
    override val busSubwayLabel = "버스+지하철"
    override val minSuffix = "분"
    override val hourSuffix = "시간"
    override val minWalkSuffix = "분 도보"
    override val etaPrefix = "도착 예정"
    override val notAvailable = "이용 불가"
    override val stopsAway = "정거장 전"
    override val listenToStory = "스토리 듣기"
    override val getOffAt = "하차역:"
    override val currentLocation = "현재 위치"

    override val endNaviTitle = "내비를 종료할까요?"
    override val endNaviMessage = "안내를 중단하고 이전 화면으로 돌아가요."
    override val confirm = "종료"
    override val cancel = "취소"

    override val noRecommendations = "아직 추천 장소가 없어요"
    override val noRecommendationsDesc = "관심사를 알려주시면 맞춤 장소를 찾아드릴게요"
    override val noSavedPhrases = "저장된 회화가 없어요"
    override val noSavedPhrasesDesc = "북마크하면 오프라인에서도 확인할 수 있어요"
}
