package com.ohmyguide.app.ui.theme.strings

import com.ohmyguide.app.ui.theme.AppStrings

object ZhCnStrings : AppStrings {
    override val appName = "Oh My Guide"
    override val back = "返回"
    override val send = "发送"
    override val remove = "移除"
    override val stop = "停止"
    override val skip = "跳过"
    override val restore = "恢复"
    override val map = "地图"
    override val next = "下一步"

    override val navHome = "首页"
    override val navExplore = "探索"
    override val navPhrases = "用语"

    override val splashSubtitle = "您的专属韩国旅游导览服务"

    override val welcomeGreeting = "安妞！\uD83D\uDC4B"
    override val welcomeIntro = "我是你的韩国导游"
    override val welcomeDesc = "发现精彩景点，\n像当地人一样导航，\n获得个性化导览。"
    override val signInGoogle = "使用 Google 登录"
    override val signInHint = "一键登录，获取您的专属导览"

    override val onboardLangPrompt = "寻找您附近的最佳景点！\n为了提供最佳体验，\n请选择您偏好的语言。"
    override val onboardGenderPrompt = "太好了！请问您的性别是？"
    override val onboardAgePrompt = "很好！请问您几岁？"
    override val onboardCountryPrompt = "您来自哪个国家？"
    override val onboardCompanionPrompt = "太棒了！您和谁一起旅行？"
    override val onboardGpsPrompt = "太好了！最后，请允许位置访问，\n让我们一起探索。"
    override val allowLocation = "允许位置访问"
    override val enterAge = "请输入年龄"
    override val yearsOld = "岁"
    override val female = "女性"
    override val male = "男性"
    override val friends = "朋友"
    override val family = "家人"
    override val solo = "独自"

    override val detectingLocation = "正在检测您的位置..."
    override val yourLocation = "您的位置"
    override val categoryGreeting = "嗨！我是 Oh My Guide\n我现在就帮你找到附近的完美景点！"
    override val categoryPrompt = "告诉我你感兴趣的东西"
    override val categoryDone = "很棒的选择！让我为你找到最佳景点... \uD83C\uDFAF"
    override val chooseInterests = "选择你感兴趣的！"
    override val addMoreOrSend = "好选择！继续添加或发送"
    override val categoriesSelected = "个类别已选择"

    override val findingSpots = "正在寻找精彩景点..."
    override val scanningNearby = "根据您的兴趣\n扫描附近的景点"

    override val curatingSpots = "精选景点中..."
    override val reset = "重置"
    override val near = "附近"
    override val spots = "景点"
    override val yourArea = "您的区域"
    override val backToList = "返回列表"
    override val findOtherPlaces = "寻找其他景点"
    override val goHere = "前往这里"

    override val hotThisWeek = "本周热门"
    override val courses = "路线"
    override val allCourses = "所有路线"
    override val kCulture = "K-Culture"
    override val explore = "探索"
    override val trending = "热门"
    override val diveIntoKCulture = "深入体验\nK-Culture"
    override val curatedCourses = "由本地人和K-粉丝精选的路线"
    override val noCoursesFound = "找不到路线"
    override val tryDifferentRegion = "试试不同的地区或类别"
    override val courseRoute = "路线规划"
    override val startCourseNavi = "开始路线导航"
    override val courseProgress = "路线进度"
    override val rightHere = "就在这里"

    override val destination = "目的地"
    override val tapToSeeRoutes = "点击下方查看可用路线"
    override val viewTransitRoutes = "查看交通路线"
    override val startNavigation = "开始导航"
    override val walk = "步行"
    override val enjoyScenery = "享受风景"
    override val transit = "公共交通"
    override val busAndSubway = "公交和地铁"
    override val taxi = "出租车"
    override val taxiCar = "出租车 / 汽车"
    override val transfer = "换乘"
    override val subway = "地铁"
    override val direct = "直达"
    override val stopsUnit = "站"

    override val walkingTo = "步行前往"
    override val transitTo = "搭乘公共交通前往"
    override val drivingTo = "驾车前往"
    override val yesShowMe = "好的，带我看看！"
    override val iveArrived = "我到了！"
    override val listen = "收听"
    override val photo = "照片"
    override val prices = "价格"

    override val nowPlaying = "播放中\u2026"
    override val paused = "已暂停"
    override val backToGuide = "返回导览"

    override val koreanPhrasesTitle = "韩语短语"
    override val koreanPhrasesSubtitle = "旅客韩语常用语"
    override val saved = "已保存"
    override val bookmarkHint = "点击书签保存用语，离线也能快速查看！"
    override val phrasesUnit = "个短语"

    override val myPage = "我的页面"
    override val visitHistory = "参观记录"
    override val placesVisitedDesc = "您去过的地方"
    override val bookmarks = "书签"
    override val savedPlacesDesc = "已保存的地点和用语"
    override val storyArchive = "故事档案"
    override val storiesListenedDesc = "您听过的故事"
    override val language = "语言"
    override val notifications = "通知"
    override val on = "开启"
    override val theme = "主题"
    override val light = "浅色"
    override val traveler = "旅客"
    override val food = "美食"
    override val culture = "文化"
    override val signOut = "退出登录"

    override val locating = "定位中..."
    override val mapView = "地图视图"
    override val explorePlaces = "探索您周围的景点"

    override val hours = "营业时间"
    override val fee = "费用"
    override val distance = "距离"
    override val preview = "预览"
    override val placeNo = "否"
    override val placeGo = "前往"
}