package com.ohmyguide.app.ui.theme.strings

import com.ohmyguide.app.ui.theme.AppStrings

object ZhTwStrings : AppStrings {
    override val appName = "Oh My Guide"
    override val back = "返回"
    override val send = "發送"
    override val remove = "移除"
    override val stop = "停止"
    override val skip = "跳過"
    override val restore = "恢復"
    override val map = "地圖"
    override val next = "下一步"

    override val navHome = "首頁"
    override val navExplore = "探索"
    override val navPhrases = "用語"

    override val splashSubtitle = "您的專屬韓國旅遊導覽服務"

    override val welcomeGreeting = "安妞！\uD83D\uDC4B"
    override val welcomeIntro = "我是你的韓國導遊"
    override val welcomeDesc = "發現精彩景點，\n像當地人一樣導航，\n獲得個人化導覽。"
    override val signInGoogle = "使用 Google 登入"
    override val signInHint = "一鍵登入，取得您的專屬導覽"
    override val loginSuccess = "登入成功。"

    override val onboardLangPrompt = "尋找您附近的最佳景點！\n為了提供最佳體驗，\n請選擇您偏好的語言。"
    override val onboardGenderPrompt = "太好了！請問您的性別是？"
    override val onboardAgePrompt = "很好！請問您幾歲？"
    override val onboardCountryPrompt = "您來自哪個國家？"
    override val onboardCompanionPrompt = "太棒了！您和誰一起旅行？"
    override val onboardGpsPrompt = "太好了！最後，請允許位置存取，\n讓我們一起探索。"
    override val allowLocation = "允許位置存取"
    override val enterAge = "請輸入年齡"
    override val yearsOld = "歲"
    override val female = "女性"
    override val male = "男性"
    override val friends = "朋友"
    override val family = "家人"
    override val solo = "獨自"

    override val detectingLocation = "正在偵測您的位置..."
    override val yourLocation = "您的位置"
    override val categoryGreeting = "嗨！我是 Oh My Guide\n我現在就幫你找到附近的完美景點！"
    override val categoryPrompt = "告訴我你感興趣的東西"
    override val categoryDone = "很棒的選擇！讓我為你找到最佳景點... \uD83C\uDFAF"
    override val chooseInterests = "選擇你感興趣的！"
    override val addMoreOrSend = "好選擇！繼續添加或發送"
    override val categoriesSelected = "個類別已選擇"

    override val findingSpots = "正在尋找精彩景點..."
    override val scanningNearby = "根據您的興趣\n掃描附近的景點"

    override val curatingSpots = "精選景點中..."
    override val reset = "重置"
    override val near = "附近"
    override val spots = "景點"
    override val yourArea = "您的區域"
    override val backToList = "返回列表"
    override val findOtherPlaces = "尋找其他景點"
    override val goHere = "前往這裡"

    override val hotThisWeek = "本週熱門"
    override val courses = "路線"
    override val allCourses = "所有路線"
    override val kCulture = "K-Culture"
    override val explore = "探索"
    override val trending = "熱門"
    override val diveIntoKCulture = "深入體驗\nK-Culture"
    override val curatedCourses = "由在地人和K-粉絲精選的路線"
    override val noCoursesFound = "找不到路線"
    override val tryDifferentRegion = "試試不同的地區或類別"
    override val exploreThisCourse = "探索此路線"
    override val seeAllCourses = "查看所有路線"
    override val swipeToDiscover = "滑動發現更多"
    override val themeKpopTitle = "K-Pop Demon\nHunters"
    override val themeKpopSubtitle = "Follow the hottest idol spots in Hongdae & Mapo"
    override val themeBtsTitle = "BTS ARMY\nSeoul Tour"
    override val themeBtsSubtitle = "Walk the streets where BTS made history"
    override val themeSsafyTitle = "SSAFY Lunch\nWalk Course"
    override val themeSsafySubtitle = "The best lunch break walking route around SSAFY campus"
    override val courseRoute = "路線規劃"
    override val startCourseNavi = "開始路線導航"
    override val courseProgress = "路線進度"
    override val rightHere = "就在這裡"

    override val destination = "目的地"
    override val tapToSeeRoutes = "點擊下方查看可用路線"
    override val viewTransitRoutes = "查看交通路線"
    override val startNavigation = "開始導航"
    override val walk = "步行"
    override val enjoyScenery = "享受風景"
    override val transit = "大眾運輸"
    override val busAndSubway = "公車和地鐵"
    override val taxi = "計程車"
    override val taxiCar = "計程車 / 汽車"
    override val transfer = "轉乘"
    override val subway = "地鐵"
    override val direct = "直達"
    override val stopsUnit = "站"

    override val walkingTo = "步行前往"
    override val transitTo = "搭乘大眾運輸前往"
    override val drivingTo = "開車前往"
    override val yesShowMe = "好的，帶我看看！"
    override val iveArrived = "我到了！"
    override val listen = "收聽"
    override val photo = "照片"
    override val prices = "價格"

    override val loading = "載入中\u2026"
    override val nowPlaying = "播放中\u2026"
    override val paused = "已暫停"
    override val backToGuide = "返回導覽"
    override val listenToGuide = "收聽導覽"

    override val koreanPhrasesTitle = "韓語短語"
    override val koreanPhrasesSubtitle = "旅客韓語常用語"
    override val saved = "已儲存"
    override val bookmarkHint = "點擊書籤保存用語，離線也能快速查看！"
    override val phrasesUnit = "個短語"

    override val myPage = "我的頁面"
    override val visitHistory = "參觀記錄"
    override val placesVisitedDesc = "您去過的地方"
    override val bookmarks = "書籤"
    override val savedPlacesDesc = "已儲存的地點和用語"
    override val storyArchive = "故事檔案"
    override val storiesListenedDesc = "您聽過的故事"
    override val language = "語言"
    override val notifications = "通知"
    override val on = "開啟"
    override val theme = "主題"
    override val light = "淺色"
    override val traveler = "旅客"
    override val food = "美食"
    override val culture = "文化"
    override val signOut = "登出"

    override val locating = "定位中..."
    override val mapView = "地圖檢視"
    override val explorePlaces = "探索您周圍的景點"

    override val hours = "營業時間"
    override val fee = "費用"
    override val distance = "距離"
    override val preview = "預覽"
    override val placeNo = "否"
    override val placeGo = "前往"

    override val transitRoutes = "公車路線"
    override val searchingRoutes = "正在搜尋路線..."
    override val noTransitRoutes = "找不到大眾運輸路線"
    override val tryWalkOrCar = "可以試試步行或搭車"
    override val filterAll = "全部"
    override val busLabel = "公車"
    override val busSubwayLabel = "公車+地鐵"
    override val minSuffix = "分鐘"
    override val hourSuffix = "小時"
    override val minWalkSuffix = "分鐘步行"
    override val etaPrefix = "預計到達"
    override val notAvailable = "不可用"
    override val stopsAway = "站前到達"
    override val listenToStory = "收聽故事"
    override val getOffAt = "在此下車:"
    override val currentLocation = "目前位置"

    override val endNaviTitle = "結束導航？"
    override val endNaviMessage = "確定要停止導航嗎？"
    override val confirm = "結束"
    override val cancel = "取消"

    override val noRecommendations = "暫無推薦景點"
    override val noRecommendationsDesc = "告訴我們你的興趣，為你找到專屬景點"
    override val noSavedPhrases = "沒有儲存的短語"
    override val noSavedPhrasesDesc = "收藏短語以便離線查看"
}