services:
  spring-boot:
    image: oh-my-guide-backend:latest
    container_name: spring-boot
    env_file: ../../backend/.env
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    external: true
