services:
  fastapi:
    image: oh-my-guide-ai:latest
    container_name: fastapi
    env_file: ../../ai/.env
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    external: true
