services:
  fastapi:
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
    networks:
      - s14p21e103_app-network
  spring-boot:
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - AI_SERVER_URL=http://fastapi:8000
    networks:
      - s14p21e103_app-network

networks:
  s14p21e103_app-network:
    external: true
